import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:personalwallettracker/services/firebase/auth/auth_checker.dart';
import 'package:personalwallettracker/services/notifications/notification.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure



Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await LocalNotificationService.initialize();

  //LocalNotificationService.scheduleDailyReminderAtFourPM(id: 4444, title:'title', body:'test body');
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      color: Colors.deepPurple,
      home: AuthChecker(),
    );
  }
}